In [28]:
import numpy as np
np_array = np.array( [0, 1, 2, 3] )
# Creating an array with ten elements initialized as zero
np_zero_array = np.zeros(10)

Câu 1: Sinh viên cho ví vụ về phép cộng, trừ hai ma trận numpy

In [29]:
import numpy as np
matrix_a = np.array( [ [1, 2], [3, 4] ] ) #Tạo ma trận
matrix_b = np.array( [ [5, 6], [7, 8] ] )

print("Ma trận A:") #In ma trận để xác định trước và sau khi tính
print (matrix_a)
print("Ma trận B:")
print(matrix_b)

print("Tổng của 2 ma trận là:") #Phép cộng 2 ma trận
matrix_sum = matrix_a + matrix_b
print(matrix_sum)

print ("Hiệu của 2 ma trận là:") #Trừ 2 ma trận
matrix_minor = matrix_a - matrix_b
print(matrix_minor)



Ma trận A:
[[1 2]
 [3 4]]
Ma trận B:
[[5 6]
 [7 8]]
Tổng của 2 ma trận là:
[[ 6  8]
 [10 12]]
Hiệu của 2 ma trận là:
[[-4 -4]
 [-4 -4]]


In [30]:
import numpy as np

def predict(data, w):
    return data.dot(w)


# w is the vector of weights
w = np.array([0.1, 0.2, 0.3])

# matrices as input datasets
data1 = np.array([0.3, 1.5, 2.8])

data2 = np.array([0.5, 0.4, 0.9])

data3 = np.array([2.3, 3.1, 0.5])


data_in = np.array([data1[0],data2[0],data3[0]])

print('Predicted value: $%.2f' %  predict(data_in, w) )

Predicted value: $0.82


In [31]:
import numpy as np
from sklearn.linear_model import LinearRegression
# X is a matrix that represents the training dataset
# y is a vector of weights, to be associated with input dataset
X = np.array([[3], [5], [7], [9], [11]]).reshape(-1, 1)
y = [8.0, 9.1, 10.3, 11.4, 12.6]
lreg_model = LinearRegression()
lreg_model.fit(X, y)
# New data (unseen before)
new_data = np.array([[13]])
print('Model Prediction for new data: $%.2f' % lreg_model.predict(new_data)[0])
# %

Model Prediction for new data: $13.73


In [32]:
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df.head()
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


Câu 2: Sinh viên sử dụng pandas xử lý các yêu cầu sau:

In [33]:
import pandas as pd

# Create the DataFrame
data = {
    'X': [78, 85, 80, 96, 86],
    'Y': [84, 94, 83, 94, 86],
    'Z': [86, 97, 73, 96, 83]
}

df = pd.DataFrame(data)
print(df)

import numpy as np

# Convert to NumPy array
array = df.to_numpy()

# Example: Calculate mean of each column
mean_values = np.mean(array, axis=0)
print("Mean of X, Y, Z:", mean_values)

# Example: Standard deviation
std_values = np.std(array, axis=0)
print("Standard deviation of X, Y, Z:", std_values)

df.to_csv('cau2.csv', index=False)


    X   Y   Z
0  78  84  86
1  85  94  97
2  80  83  73
3  96  94  96
4  86  86  83
Mean of X, Y, Z: [85.  88.2 87. ]
Standard deviation of X, Y, Z: [6.26099034 4.83321839 8.87693641]


In [34]:
#2.1  Đọc CSV thành Dataframe và hiển thị
import pandas as pd

df = pd.read_csv('cau2.csv')  # Đọc file CSV
print(df)  # Hiển thị nội dung

first_col = df.columns[0]
df.set_index(first_col, inplace=True)
df.index.name = 'id'


    X   Y   Z
0  78  84  86
1  85  94  97
2  80  83  73
3  96  94  96
4  86  86  83


In [35]:
#2.2 Hãy chuyển index mặc định thành giá trị cột id

import pandas as pd

# Tạo bảng
data = {
    'X': [78, 85, 80, 96, 86],
    'Y': [84, 94, 83, 94, 86],
    'Z': [86, 97, 73, 96, 83]
}

df = pd.DataFrame(data)

# Đặt lại index là cột số thứ tự ban đầu
df.reset_index(inplace=True)
df.set_index('index', inplace=True)
df.index.name = 'id'

print(df)

     X   Y   Z
id            
0   78  84  86
1   85  94  97
2   80  83  73
3   96  94  96
4   86  86  83


In [36]:
#2.3 Sắp xếp dữ liễu theo nhiều cột (sort)
df_sorted = df.sort_values(by=['X', 'Y'], ascending=[False, True])
print("\n Sau khi sắp xếp theo X giảm dần và Y tăng dần:")
print(df_sorted)


 Sau khi sắp xếp theo X giảm dần và Y tăng dần:
     X   Y   Z
id            
3   96  94  96
4   86  86  83
1   85  94  97
2   80  83  73
0   78  84  86


In [37]:
#2.4 Chọn một cột cụ thể và hiển thị nó
print("\n Cột Y:")
print(df['Y'])


 Cột Y:
id
0    84
1    94
2    83
3    94
4    86
Name: Y, dtype: int64


In [38]:
#2.5 - Chọn 2 hàng đầu tiền và hiển thị chúng
print("\n Hai hàng đầu tiên:")
print(df.head(2))


 Hai hàng đầu tiên:
     X   Y   Z
id            
0   78  84  86
1   85  94  97


In [39]:
#2.6 Hãy chọ một hàng dựa trên một điều kiện giá trị của cột
print("\n Hàng có X > 90:")
print(df[df['X'] > 90])


 Hàng có X > 90:
     X   Y   Z
id            
3   96  94  96


In [40]:
#2.7 - Thay đổi một vài giá trị thành NaN ở CSV, sau đó đọc lên thành Dataframe và thay thế chúng bằng giá trị 0
df.loc[2, 'Y'] = np.nan
df.loc[4, 'Z'] = np.nan
print("\n Sau khi gán NaN:")
print(df)

df.fillna(0, inplace=True)
print("\n Sau khi thay thế NaN bằng 0:")
print(df)


 Sau khi gán NaN:
     X     Y     Z
id                
0   78  84.0  86.0
1   85  94.0  97.0
2   80   NaN  73.0
3   96  94.0  96.0
4   86  86.0   NaN

 Sau khi thay thế NaN bằng 0:
     X     Y     Z
id                
0   78  84.0  86.0
1   85  94.0  97.0
2   80   0.0  73.0
3   96  94.0  96.0
4   86  86.0   0.0


In [41]:
#2.8 Ở cột Z chuyển giá trị lớn hơn 90 là True và nhỏ hơn là False trong Dataframe
df['Z'] = df['Z'] > 90
print("\n Cột Z sau khi chuyển thành True/False:")
print(df)


 Cột Z sau khi chuyển thành True/False:
     X     Y      Z
id                 
0   78  84.0  False
1   85  94.0   True
2   80   0.0  False
3   96  94.0   True
4   86  86.0  False


In [42]:
#2.9  Chuyển Dataframe trên thành 2 Dataframe d1 và d2; d1 chứ cột X và Y, d2 chứa cột Z;
#cuối cùng d3 là thành quả của nối 2 Dataframe d1 và d2
d1 = df[['X', 'Y']]
d2 = df[['Z']]
d3 = pd.concat([d1, d2], axis=1)
print("\n DataFrame d3 sau khi nối d1 và d2:")
print(d3)


 DataFrame d3 sau khi nối d1 và d2:
     X     Y      Z
id                 
0   78  84.0  False
1   85  94.0   True
2   80   0.0  False
3   96  94.0   True
4   86  86.0  False


In [43]:
#2.10  Dùng tính năng thống kê hãy hiển thị kết quả thông kể các giá trị thuộc tính của Dataframe
print("\n Thống kê mô tả của d3:")
print(d3.describe())


 Thống kê mô tả của d3:
          X          Y
count   5.0   5.000000
mean   85.0  71.600000
std     7.0  40.283992
min    78.0   0.000000
25%    80.0  84.000000
50%    85.0  86.000000
75%    86.0  94.000000
max    96.0  94.000000


Câu 4: Sinh viên hoàn thành code phát hiện spam với SVMs và Linear regression

In [44]:

from google.colab import drive
drive.mount('/content/drive') #M



MessageError: Error: credential propagation was unsuccessful

In [60]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [61]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/sms_spam_perceptron.csv')
print(df.head())  # Kiểm tra vài dòng đầu


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/sms_spam_perceptron.csv'

In [63]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# Đọc file CSV từ Drive
df = pd.read_csv('/content/drive/MyDrive/sms_spam_perceptron.csv')

# Chuyển nhãn 'Type' thành số: spam = 1, ham = 0
df['label'] = df['Type'].map({'spam': 1, 'ham': 0})

# Tách đặc trưng và nhãn
X = df[['buy', 'sex']]
y = df['label']

# Chia dữ liệu thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Khởi tạo và huấn luyện mô hình SVM
svm = SVC(kernel='linear', C=1.0, random_state=0)
svm.fit(X_train, y_train)

# Dự đoán
y_pred = svm.predict(X_test)

# Đánh giá kết quả
print(" Độ chính xác:", accuracy_score(y_test, y_pred))
print(" Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/sms_spam_perceptron.csv'

**Câu 5.  Sinh viên cho biết chức năng của phương thức genfromtxt() trong thư viện numpy.**

Load data from a text file, with missing values handled as specified.
Each line past the first skip_header lines is split at the delimiter character, and characters following the comments character are discarded.

*   Đọc dữ liệu từ file văn bản: mỗi dòng trong file được tách theo ký tự phân cách (delimiter).
*   Chuyển dữ liệu thành mảng NumPy: dữ liệu sau khi đọc sẽ được lưu dưới dạng ndarray.
*   Xử lý giá trị thiếu: nếu file có ô trống hoặc ký hiệu đặc biệt, genfromtxt() có thể thay thế bằng giá trị mặc định (ví dụ: 0 hoặc NaN).
*   Tùy chỉnh linh hoạt: cho phép bỏ qua dòng đầu (header), chọn cột cụ thể, định nghĩa kiểu dữ liệu cho từng cột, và bỏ qua ký tự chú thích


---


1.    Hữu ích khi dữ liệu không hoàn chỉnh hoặc cần xử lý linh hoạt (bỏ dòng, chọn cột, đổi kiểu dữ liệu).
2.   genfromtxt() thường được dùng cho các bài toán nhập dữ liệu thô trước khi phân tích hoặc huấn luyện mô hình



.


In [64]:
#Vài syntax của thư viện genfromtxt
numpy.genfromtxt(
    fname,              # tên file hoặc đường dẫn
    delimiter=',',      # ký tự phân cách (ví dụ: dấu phẩy cho CSV)
    dtype=float,        # kiểu dữ liệu (float, int, str…)
    skip_header=1,      # bỏ qua số dòng đầu (thường là tiêu đề)
    missing_values='',  # ký hiệu giá trị thiếu
    filling_values=0    # giá trị thay thế cho dữ liệu thiếu
)


NameError: name 'numpy' is not defined

In [57]:
#Vị dụ dùng genformtxt để modify data
import pandas as pd
import numpy as np
# Create the DataFrame
data = {
    'X': [78, 85, 80,np.nan,86],
    'Y': [84, 94, 83, 94, 86],
    'Z': [86, 97,np.nan,96, 83]
}

df = pd.DataFrame(data)
print(df)
df.to_csv('output.csv', index=False)


data = np.genfromtxt('output.csv', delimiter=',', skip_header=1,filling_values=0)
print ("\nData sau khi dùng genfromtxt:")
print(data)


      X   Y     Z
0  78.0  84  86.0
1  85.0  94  97.0
2  80.0  83   NaN
3   NaN  94  96.0
4  86.0  86  83.0

Data sau khi dùng genfromtxt:
[[78. 84. 86.]
 [85. 94. 97.]
 [80. 83.  0.]
 [ 0. 94. 96.]
 [86. 86. 83.]]


Câu 3. Sinh viên tự tìm hiểu thực hiện lại ví dụ dùng mô hình Linear Regression trong thư viện scikit-learning bằng các thư viện sau:  -TensorFlow - Keras - PyTorch
Cho biết cảm nghĩ về việc dùng 4 thư viện này

In [56]:
import tensorflow as tf
import numpy as np

# Training data (convert to tensors)
X = tf.constant([[3.0], [5.0], [7.0], [9.0], [11.0]], dtype=tf.float32)
y = tf.constant([8.0, 9.1, 10.3, 11.4, 12.6], dtype=tf.float32)

# Define model parameters
W = tf.Variable(tf.random.normal([1, 1], dtype=tf.float32))
b = tf.Variable(tf.random.normal([1], dtype=tf.float32))

# Linear regression model
def model(x):
    return tf.matmul(x, W) + b

# Loss function
def loss_fn(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - tf.squeeze(y_pred)))

# Optimizer
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Training loop
for epoch in range(1000):
    with tf.GradientTape() as tape:
        predictions = model(X)
        loss = loss_fn(y, predictions)
    gradients = tape.gradient(loss, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))

# Prediction
new_data = tf.constant([[13.0]], dtype=tf.float32)
prediction = model(new_data)

print("TensorFlow Prediction for new data: %.2f" % prediction.numpy()[0][0])


TensorFlow Prediction for new data: 13.95


Nhận xét:
TensorFlow cho phép kiểm soát chi tiết quá trình huấn luyện nhưng code dài và phức tạp hơn scikit-learn.

Thư viện Keras :

In [55]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

# Training data
X = np.array([[3], [5], [7], [9], [11]], dtype=float)
y = np.array([8.0, 9.1, 10.3, 11.4, 12.6], dtype=float)

# Build model
model = keras.Sequential([
    layers.Dense(1, input_shape=(1,))
])

# Compile model
model.compile(optimizer='sgd', loss='mse')

# Train model
model.fit(X, y, epochs=500, verbose=0)

# Prediction
new_data = np.array([[13]], dtype=float)
prediction = model.predict(new_data)

print("Keras Prediction for new data: %.2f" % prediction[0][0])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Keras Prediction for new data: 14.65


Nhận xét:
Keras có cú pháp rất ngắn gọn, dễ hiểu, gần giống scikit-learn nhưng vẫn mang tính Deep Learning. Kết quả trả về lâu nhất trong 4 thư viện.

Thư Viện Pytorch:

In [45]:
import torch
import torch.nn as nn
import torch.optim as optim

# Training data
X = torch.tensor([[3.0], [5.0], [7.0], [9.0], [11.0]])
y = torch.tensor([[8.0], [9.1], [10.3], [11.4], [12.6]])

# Define model
model = nn.Linear(1, 1)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(1000):
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

# Prediction
new_data = torch.tensor([[13.0]])
prediction = model(new_data)

print("PyTorch Prediction for new data: %.2f" % prediction.item())


PyTorch Prediction for new data: 13.93


PyTorch cho cảm giác lập trình thủ công và linh hoạt, giúp hiểu rõ từng bước huấn luyện nhưng phải viết nhiều code hơn.

Thư viện scikit-learning

In [54]:
import numpy as np
from sklearn.linear_model import LinearRegression
# X is a matrix that represents the training dataset
# y is a vector of weights, to be associated with input dataset
X = np.array([[3], [5], [7], [9], [11]]).reshape(-1, 1)
y = [8.0, 9.1, 10.3, 11.4, 12.6]
lreg_model = LinearRegression()
lreg_model.fit(X, y)
# New data (unseen before)
new_data = np.array([[13]])
print('Model Prediction for new data: $%.2f' % lreg_model.predict(new_data)[0]  )



Model Prediction for new data: $13.73


Nhận xét:
Kết quả trả về nhanh, code đơn giản và dễ sử dụng

Câu 6.  Sinh viên hoàn thiện code Decision Trees trên và đánh giá kết quả nhận được so với phương pháp Logistic regression.

In [48]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [50]:
!ls /content/drive/MyDrive/ML


phishing_dataset.csv


Phương pháp Logistic regression:

In [51]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Load dataset from Google Drive
phishing_dataset = np.genfromtxt(
    '/content/drive/MyDrive/ML/phishing_dataset.csv',
    delimiter=',',
    dtype=np.int32
)

# Split features and labels
samples = phishing_dataset[:, :-1]
targets = phishing_dataset[:, -1]

# Train-test split
training_samples, testing_samples, training_targets, testing_targets = train_test_split(
    samples,
    targets,
    test_size=0.2,
    random_state=0
)

# Logistic Regression model
log_classifier = LogisticRegression(max_iter=1000)

# Train model
log_classifier.fit(training_samples, training_targets)

# Prediction
predictions = log_classifier.predict(testing_samples)

# Accuracy
accuracy = 100.0 * accuracy_score(testing_targets, predictions)

print("Logistic Regression accuracy:", accuracy)



Logistic Regression accuracy: 92.8119349005425


Phương pháp Decision Tree

In [53]:
from sklearn import tree
from sklearn.metrics import accuracy_score

# Decision Tree model
tree_classifier = tree.DecisionTreeClassifier(random_state=0)

# Train model
tree_classifier.fit(training_samples, training_targets)

# Predict
tree_predictions = tree_classifier.predict(testing_samples)

# Accuracy
tree_accuracy = 100.0 * accuracy_score(testing_targets, tree_predictions)

print("Decision Tree accuracy:", tree_accuracy)


Decision Tree accuracy: 96.42857142857143


=> Decision Tree cho độ chính xác cao hơn Logistic Regression trên tập dữ liệu phishing. Tuy nhiên, Logistic Regression có ưu điểm là mô hình đơn giản và ổn định hơn.

**Nhận xét:**

Kết quả thực nghiệm cho thấy mô hình Decision Tree đạt độ chính xác cao hơn Logistic Regression trong bài toán phát hiện phishing website.

Nguyên nhân là Decision Tree có khả năng học các mối quan hệ phi tuyến giữa các thuộc tính, trong khi Logistic Regression chỉ phù hợp với các ranh giới tuyến tính.

Tuy nhiên, Decision Tree có nguy cơ overfitting nếu không giới hạn độ sâu của cây.